name: Daily Auction Scrape

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver
          # Check if chromedriver link exists and remove if necessary
          if [ -f /usr/bin/chromedriver ]; then
            sudo rm /usr/bin/chromedriver
          fi
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape_auctions.py

      - name: Debug directory contents before rename
        run: |
          ls -la auction_exports/
          find auction_exports/ -type f

      - name: Rename Excel file with date
        run: |
          for file in auction_exports/*.xls; do
            if [ -f "$file" ]; then
              mv "$file" "auction_exports/ibbi_auctions_$(date +%Y%m%d).xls"
              break
            fi
          done

      - name: Debug directory contents after rename
        run: |
          ls -la auction_exports/
          find auction_exports/ -type f

      - name: Commit and push downloaded Excel file
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # Add .xls files if they exist
          ls auction_exports/*.xls >/dev/null 2>&1 && git add auction_exports/*.xls || echo "No .xls files to add"
          git commit -m "Update auction Excel file for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
